### ISSUE TITLE
Is this similar to Z or FASD?

### ISSUE THREAD

**Issue by molleweide** [ingram1107/origin.nvim#3]
Hi,

I was looking for a fast way of navigating directories. I use `fasd` in the terminal and I was wondering if this works similarly to fasd or z?

Cheers 😃

**Comment by ingram1107** [comment]
No, this Neovim plugin has totally different purpose than fasd or z. It merely gets the current working directory, and use the logic set by `default_source` in order to set the desirable project root after Neovim fresh startup.

There are several plugins that do the job for you, here is what I have found so far:
[autojump.vim](https://github.com/trotter/autojump.vim)
[vim-denite-z](https://github.com/rafi/vim-denite-z)
[zoxide.vim](https://github.com/nanotee/zoxide.vim)
[teleport.vim](https://github.com/PsychoLlama/teleport.vim)
[fasd.vim](https://github.com/laggardkernel/fasd.vim) (deprecated, but it shows you that you can incorporate it into fzf)

**Comment by molleweide** [comment]
Thank you for replying and listing all these other programs!!

**Comment by ingram1107** [comment]
anytime
